export const profile = {
  name: "Anand Shukla",
  location: "Mirzapur, Uttar Pradesh, India",
  phone: "+91-9076823328",
  email: "aanandd9076@gmail.com",
  education: {
    institution: "Indian Institute of Information Technology Nagpur",
    shortInstitution: "IIIT Nagpur",
    degree: "Bachelor of Technology in Electronics and Communication Engineering",
    shortDegree: "B.Tech ECE",
    timeline: "Nov 2022 – Jun 2026",
    gradYear: "2026",
    coursework: [
      "Data Structures & Algorithms",
      "Operating Systems",
      "Object-Oriented Programming",
      "Database Management Systems",
      "Computer Networks",
    ],
  },
  links: {
    portfolio: "https://anand-shukla02.onrender.com/",
    resume: "https://drive.google.com/file/d/1tppKMCDPsWeHdtFIaMD-jWEUdVSz9hW-/view?usp=sharing",
    linkedin: "https://www.linkedin.com/in/aanandd02",
    github: "https://github.com/aanandd02",
    leetcode: "https://leetcode.com/u/aanandd02",
  },
  achievements: {
    leetcode: {
      title: "LeetCode Knight",
      rating: 2006,
      topPercent: "2.44%",
      problemsSolved: "400+",
    },
    deployedSystems: "6+ backend systems deployed using Node.js, MongoDB, MySQL, and AWS",
  },
  experience: [
    {
      company: "Synup",
      role: "SDE Intern",
      timeline: "Jan 2026 – Apr 2026",
      location: "Bengaluru, Karnataka, India",
      highlights: [
        "Architected a serverless microservices pipeline using AWS Lambda, MySQL and Elasticsearch for event-driven fan-out processing, reducing failures by ~40%",
        "Resolved a critical race condition using transaction-safe MySQL updates across concurrent services, improving consistency and reliability of distributed workflows",
      ],
      techStack: ["AWS Lambda", "MySQL", "Elasticsearch", "Microservices", "Event-Driven Architecture"],
    },
    {
      company: "BrandX",
      role: "SDE Intern",
      timeline: "Oct 2025 – Jan 2026",
      location: "Noida, India",
      highlights: [
        "Developed a concurrent-safe booking system using Node.js and MongoDB with atomic slot allocation and reservation workflows",
        "Optimized database queries and introduced compound indexing, reducing API response latency by ~35% under peak traffic",
      ],
      techStack: ["Node.js", "MongoDB", "REST APIs", "Compound Indexing"],
    },
  ],
  projects: [
    {
      name: "Enterprise RAG & Agent Platform",
      tagline: "Production-grade autonomous AI knowledge system",
      tech: ["Python", "FastAPI", "LangGraph", "Qdrant", "PostgreSQL", "Redis", "Docker", "RAGAS"],
      highlights: [
        "Hybrid retrieval with semantic chunking, embeddings, reranking, and citation-grounded answer generation",
        "LangGraph multi-tool agent supporting query rewriting, web search, PostgreSQL tools, and multi-step reasoning",
        "Async ingestion with Redis and Celery; evaluated using RAGAS for faithfulness and retrieval quality",
      ],
    },
    {
      name: "AI Code Intelligence & Review Agent",
      tagline: "Repository-aware AI coding assistant",
      tech: ["Python", "FastAPI", "React", "LLM APIs", "Qdrant", "Tree-sitter", "Docker"],
      highlights: [
        "Language-aware code chunking with Tree-sitter and vector retrieval in Qdrant",
        "Agentic workflow for repository analysis, issue investigation, and structured patch generation",
      ],
    },
    {
      name: "Multimodal Document Intelligence",
      tagline: "AI-powered document understanding pipeline",
      tech: ["Python", "FastAPI", "Vision LLM", "OCR", "OpenCV", "AWS S3", "SQS", "Lambda"],
      highlights: [
        "Multimodal invoice/document extraction combining OCR, vision-language models, and structured JSON extraction",
        "Asynchronous AWS S3/SQS/Lambda processing with confidence scoring and failure handling",
      ],
    },
  ],
  skills: {
    programming: ["Python", "Java", "JavaScript", "SQL"],
    ai: [
      "LLM Applications",
      "Prompt Engineering",
      "RAG",
      "Agentic AI",
      "Tool Calling",
      "Embeddings",
      "Semantic Search",
      "Multimodal AI",
    ],
    frameworks: [
      "LangChain",
      "LangGraph",
      "LlamaIndex",
      "Hugging Face Transformers",
      "OpenAI API",
      "Google Gemini API",
      "Ollama",
    ],
    vectorSearch: ["Qdrant", "Embeddings", "Semantic Search", "Hybrid Search", "Reranking"],
    backend: [
      "FastAPI",
      "Node.js",
      "Express.js",
      "REST APIs",
      "WebSockets",
      "JWT",
      "Microservices",
      "Event-Driven Architecture",
    ],
    databases: ["PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "DynamoDB"],
    cloudDevOps: [
      "AWS Lambda",
      "EC2",
      "API Gateway",
      "S3",
      "SQS",
      "SNS",
      "CloudWatch",
      "Docker",
      "Git",
      "GitHub",
      "Postman",
    ],
  },
};

export default profile;
